/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountSelector: typeof import('./../../src/entries/popup/component/AccountSelector.vue')['default']
    CoinList: typeof import('./../../src/entries/popup/wallet/component/CoinList.vue')['default']
    Global: typeof import('./../../src/component/Global.vue')['default']
    IconArrowLeft: typeof import('@icon-park/vue-next')['ArrowLeft']
    IconClose: typeof import('@icon-park/vue-next')['Close']
    IconDownOne: typeof import('@icon-park/vue-next')['DownOne']
    IconFileSuccess: typeof import('@icon-park/vue-next')['FileSuccess']
    ImportBackUp: typeof import('./../../src/entries/popup/component/ImportBackUp.vue')['default']
    ImportChoose: typeof import('./../../src/entries/popup/wallet/component/ImportChoose.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NInput: typeof import('naive-ui')['NInput']
    NModal: typeof import('naive-ui')['NModal']
    NoAccount: typeof import('./../../src/entries/popup/wallet/component/NoAccount.vue')['default']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NUpload: typeof import('naive-ui')['NUpload']
    PageHeader: typeof import('./../../src/component/PageHeader.vue')['default']
    PasswordSetting: typeof import('./../../src/entries/popup/component/PasswordSetting.vue')['default']
    PasswordUnlock: typeof import('./../../src/entries/popup/component/PasswordUnlock.vue')['default']
    PopupBottom: typeof import('./../../src/component/PopupBottom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TokenSelector: typeof import('./../../src/entries/popup/wallet/component/TokenSelector.vue')['default']
    TopNav: typeof import('./../../src/entries/popup/wallet/component/TopNav.vue')['default']
    WalletHeader: typeof import('./../../src/entries/popup/wallet/component/WalletHeader.vue')['default']
  }
}
