/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./../../src/entries/options/App.vue')['default']
    Global: typeof import('./../../src/components/Global.vue')['default']
    Main: typeof import('./../../src/components/Main.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NetworkManager: typeof import('./../../src/entries/setting/NetworkManager.vue')['default']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NoAccount: typeof import('./../../src/entries/wallet/components/NoAccount.vue')['default']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NTable: typeof import('naive-ui')['NTable']
    PasswordSetting: typeof import('./../../src/entries/popup/components/PasswordSetting.vue')['default']
    PasswordUnlock: typeof import('./../../src/entries/popup/components/PasswordUnlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectNetwork: typeof import('./../../src/entries/setting/SelectNetwork.vue')['default']
    SettingLanguage: typeof import('./../../src/entries/setting/SettingLanguage.vue')['default']
    Test: typeof import('./../../src/components/Test.vue')['default']
    TokenSelector: typeof import('./../../src/entries/wallet/components/TokenSelector.vue')['default']
    TopHandle: typeof import('./../../src/components/TopHandle.vue')['default']
    TopNav: typeof import('./../../src/entries/popup/components/TopNav.vue')['default']
    Wallet: typeof import('./../../src/entries/wallet/index.vue')['default']
    WalletHeader: typeof import('./../../src/entries/wallet/components/WalletHeader.vue')['default']
  }
}
