/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddCustomNetwork: typeof import('./../../src/entries/network/AddCustomNetwork.vue')['default']
    AddNetwork: typeof import('./../../src/entries/network/AddNetwork.vue')['default']
    App: typeof import('./../../src/entries/options/App.vue')['default']
    Global: typeof import('./../../src/components/Global.vue')['default']
    IconClose: typeof import('@icon-park/vue-next')['Close']
    IconDelete: typeof import('@icon-park/vue-next')['Delete']
    IconDownOne: typeof import('@icon-park/vue-next')['DownOne']
    IconPlus: typeof import('@icon-park/vue-next')['Plus']
    Main: typeof import('./../../src/components/Main.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NetworkManager: typeof import('./../../src/entries/network/NetworkManager.vue')['default']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NModal: typeof import('naive-ui')['NModal']
    NoAccount: typeof import('./../../src/entries/wallet/components/NoAccount.vue')['default']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NTable: typeof import('naive-ui')['NTable']
    NUpload: typeof import('naive-ui')['NUpload']
    PasswordSetting: typeof import('./../../src/entries/popup/components/PasswordSetting.vue')['default']
    PasswordUnlock: typeof import('./../../src/entries/popup/components/PasswordUnlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectNetwork: typeof import('./../../src/entries/network/SelectNetwork.vue')['default']
    SettingLanguage: typeof import('./../../src/entries/setting/SettingLanguage.vue')['default']
    SettingNode: typeof import('./../../src/entries/setting/SettingNode.vue')['default']
    SettingsIndex: typeof import('./../../src/entries/setting/SettingsIndex.vue')['default']
    Test: typeof import('./../../src/components/Test.vue')['default']
    TokenSelector: typeof import('./../../src/entries/wallet/components/TokenSelector.vue')['default']
    TopHandle: typeof import('./../../src/components/TopHandle.vue')['default']
    TopNav: typeof import('./../../src/entries/popup/components/TopNav.vue')['default']
    Wallet: typeof import('./../../src/entries/wallet/index.vue')['default']
    WalletHeader: typeof import('./../../src/entries/wallet/components/WalletHeader.vue')['default']
  }
}
